charts: add supprot to pull images from  private registry
* Set all images in values.yaml so they can be overridden
  to pull from other private/public registry

* Set imagePullSecrets to be list to support for multible
  private registries, the one in default value is used for
  registry.local:9001 on StarlingX

* Change the default values for binaryData which can't be
  empty string, or it fails with:
  Error: unable to build kubernetes objects from release manifest: error
  validating "": error validating data: unknown object type "nil" in
  ConfigMap.binaryData.config.json

* docs: keep the o2 image name in local registry consistent
  with the upstream one:
  - nexus3.o-ran-sc.org:10004/o-ran-sc/pti-o2imsdms:2.0.0
  - registry.local:9001/o-ran-sc/pti-o2imsdms:2.0.0

Issue-ID: INF-336

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Change-Id: I125f9f01661cc4618bf1d81f4e0fc59d46bb9d99